# Generated by Django 4.1.4 on 2022-12-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wish_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='nickname',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Nickname',
        ),
    ]
